export const VALID_UNITS = ['pt', 'in', 'mm', 'cm', '%', 'vw', 'vh'] as const

export type ValidUnit = (typeof VALID_UNITS)[number]

const VALID_CSS_PROPERTIES = {
  flexbox: [
    'alignContent',
    'alignItems',
    'alignSelf',
    'flex',
    'flexDirection',
    'flexWrap',
    'flexFlow',
    'flexGrow',
    'flexShrink',
    'flexBasis',
    'justifyContent',
    'gap',
    'rowGap',
    'columnGap',
  ],
  layout: [
    'aspectRatio',
    'bottom',
    'display',
    'left',
    'position', // relative, absolute, static
    'right',
    'top',
    'overflow',
    'zIndex',
  ],
  dimension: ['height', 'maxHeight', 'minHeight', 'width', 'maxWidth', 'minWidth'],
  color: ['backgroundColor', 'color', 'opacity'],
  sizing: ['object-fit', 'object-position'],
  'margin & padding': [
    'margin',
    'marginHorizontal',
    'marginVertical',
    'marginTop',
    'marginRight',
    'marginBottom',
    'marginLeft',
    'padding',
    'paddingHorizontal',
    'paddingVertical',
    'paddingTop',
    'paddingRight',
    'paddingBottom',
    'paddingLeft',
  ],
  transformations: [
    'transform:rotate',
    'transform:scale',
    'transform:scaleX',
    'transform:scaleY',
    'transform:translate',
    'transform:translateX',
    'transform:translateY',
    'transform:skew',
    'transform:skewX',
    'transform:skewY',
    'transform:matrix',
    'transformOrigin',
  ],
  borders: [
    'border',
    'borderColor',
    'borderStyle',
    'borderWidth',
    'borderTop',
    'borderTopColor',
    'borderTopStyle',
    'borderTopWidth',
    'borderRight',
    'borderRightColor',
    'borderRightStyle',
    'borderRightWidth',
    'borderBottom',
    'borderBottomColor',
    'borderBottomStyle',
    'borderBottomWidth',
    'borderLeft',
    'borderLeftColor',
    'borderLeftStyle',
    'borderLeftWidth',
    'borderTopLeftRadius',
    'borderTopRightRadius',
    'borderBottomRightRadius',
    'borderBottomLeftRadius',
  ],
}
